name: ARC Easy
_target_: components.scenarios.reasoning_tasks.ARCScenario
description: AI2 ARC (Abstraction and Reasoning Corpus) Easy
dataset_name: allenai/ai2_arc
dataset_config: ARC-Easy
split: test

prompt_template: "{input}"
