name: ARC Challenge
_target_: components.scenarios.reasoning_tasks.ARCScenario
description: AI2 ARC (Abstraction and Reasoning Corpus) Challenge
dataset_name: allenai/ai2_arc
dataset_config: ARC-Challenge
split: test
num_samples: 20
prompt_template: "{input}"
