_target_: components.scenarios.perplexity_scenario.PerplexityScenario
name: perplexity_c4
dataset_name: allenai/c4
dataset_config: en
split: validation
streaming: true
text_column: text
num_samples: 100
prompt_template: "{input}"
