name: sentiment
_target_: components.scenarios.common_nlp_scenarios.SentimentScenario
dataset_name: imdb
dataset_config: null
split: test
input_key: text
target_key: label
label_map:
  0: "Negative"
  1: "Positive"
num_samples: 10
prompt_template: "Classify the sentiment of the following text as Positive or Negative.\nText: {input}\nSentiment:"
